packages = [
	"git",
	"curl",
	"wget",
	"jq",
	"flatpak",
	"zsh",
	"luajit",
	"neovim",
	"tmux",
	"fzf",
	"fd-find",
	"ripgrep",
	"bat",
]
flatpakPackages = [
	"it.mijorus.gearlever",
	"io.github.giantpinkrobots.flatsweep",
	"com.github.tchx84.Flatseal",
	"org.localsend.localsend_app",
	"dev.vencord.Vesktop",
	"io.missioncenter.MissionCenter",
]
shell = "zsh"

[git]
name = "Rob Brazier"
host = "brzr.co"

[[gitHosts]]
name = "github.com !*.github.com"
hostname = "github.com"

[[gitHosts]]
name = "codeberg.org"

[[gitHosts]]
name = "git.sr.ht"

[[gitHosts]]
name = "alter.github.com"
hostname = "github.com"
identity = "alter"

[distros]
arch = ["arch"]
ubuntu = ["ubuntu debian", "ubuntu"]
fedora = ["fedora", "nobara"]

[ssh]
[ssh.lanUsers]
jellyfin = "jellyfin"

[nerdfonts]
fonts = ["SourceCodePro", "JetBrainsMono", "FiraCode", "CascadiaCode"]
