[tools]
"github:opentofu/tofu-ls" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@tailwindcss/language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
gofumpt = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
lua-language-server = "latest"
ruff = "latest"
stylua = "latest"
superhtml = "latest"
taplo = "latest"
