[tools]
"aqua:a-h/templ" = "latest"
"aqua:doy/rbw" = "latest"
"aqua:marcosnils/bin" = "latest"
"aqua:neovim/neovim" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
"aqua:topgrade-rs/topgrade" = "latest"
"cargo:cargo-info" = "latest"
bat = "latest"
cargo-binstall = "latest"
chezmoi = "latest"
direnv = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
git-cliff = "latest"
go = "latest"
jj = "latest"
node = "lts"
python = "latest"
ripgrep = "latest"
rust = "latest"
usage = "latest"
uv = "latest"
yazi = "latest"
